### ISSUE TITLE
question about noisy_function() in 013_laplacian.md

### ISSUE THREAD

**Issue by amiltonwong** [odedstein/gp-matlab-tutorial#3]
Hi, @odedstein ,

I'm practising the section No.13 of gp-matlab-tutorial in [013_laplacian.md](https://github.com/odedstein/gp-matlab-tutorial/blob/main/013_laplacian/013_laplacian.md). There's a command: `un = noisy_function();` What specific function is `noisy_function()`?

Thanks~

**Comment by odedstein** [comment]
Hi @amiltonwong ,
There is no specific function, it's just a placeholder for any source of noise you would encounter. The picture was created by  taking a smooth function and then adding random numbers to it.
I should clarify this in the write-up.
