### ISSUE TITLE
readOBJ() does not read work as expected

### ISSUE THREAD

**Issue by GabrielePaolini** [odedstein/gp-matlab-tutorial#5]
I'm following the tutorials with Octave. 
At the moment everything is working fine, until the fourth exercise, where I'm asked to read an obj file. 
After moving the working directory to the exercise folder, I read the obj file as follows:

> [V, F] = readOBJ('data/bunny.obj');

but it does nothing and the program get stuck during the parsing.
What am I doing wrong? Is there a chance that Octave is using different implementations of the same functions, that cause the program to not work?

Cheers

**Comment by odedstein** [comment]
Hi,

This tutorial was not tested on Octave. The tutorial was made for MATLAB, and I have not run it on anything else.
readOBJ specifically is a gptoolbox function, which is also made for MATLAB (see https://github.com/alecjacobson/gptoolbox).

I have tried readOBJ on my Octave (on Ubuntu 20.04), and I am encountering the same problem as you: parsing takes forever.

I am not sure what I can do to make this work on Octave.

**Comment by GabrielePaolini** [comment]
Hi,

Ok, before giving up with Octave I just wanted to be sure that the problem was dependent on it.
I will try to recover my academic license of Matlab.

Thank you again for your support!
